document.write("    <div class=\"container-fluid\">");
document.write("	<div class=\"row\">");
document.write("		<div class=\"col-md-12\">");
document.write("			<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">");
document.write("				 ");
document.write("				<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">");
document.write("					<span class=\"navbar-toggler-icon\"><\/span>");
document.write("				<\/button> <a class=\"navbar-brand\" href=\"#\">Brand<\/a>");
document.write("				<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">");
document.write("					<ul class=\"navbar-nav\">");
document.write("						<li class=\"nav-item active\">");
document.write("							 <a class=\"nav-link\" href=\"#\">Link <span class=\"sr-only\">(current)<\/span><\/a>");
document.write("						<\/li>");
document.write("						<li class=\"nav-item\">");
document.write("							 <a class=\"nav-link\" href=\"#\">Link<\/a>");
document.write("						<\/li>");
document.write("						<li class=\"nav-item dropdown\">");
document.write("							 <a class=\"nav-link dropdown-toggle\" href=\"http:\/\/example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\">Dropdown link<\/a>");
document.write("							<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">");
document.write("								 <a class=\"dropdown-item\" href=\"#\">Action<\/a> <a class=\"dropdown-item\" href=\"#\">Another action<\/a> <a class=\"dropdown-item\" href=\"#\">Something else here<\/a>");
document.write("								<div class=\"dropdown-divider\">");
document.write("								<\/div> <a class=\"dropdown-item\" href=\"#\">Separated link<\/a>");
document.write("							<\/div>");
document.write("						<\/li>");
document.write("					<\/ul>");
document.write("					<form class=\"form-inline\">");
document.write("						<input class=\"form-control mr-sm-2\" type=\"text\"> ");
document.write("						<button class=\"btn btn-primary my-2 my-sm-0\" type=\"submit\">");
document.write("							Search");
document.write("						<\/button>");
document.write("					<\/form>");
document.write("					<ul class=\"navbar-nav ml-md-auto\">");
document.write("						<li class=\"nav-item active\">");
document.write("							 <a class=\"nav-link\" href=\"#\">Link <span class=\"sr-only\">(current)<\/span><\/a>");
document.write("						<\/li>");
document.write("						<li class=\"nav-item dropdown\">");
document.write("							 <a class=\"nav-link dropdown-toggle\" href=\"http:\/\/example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\">Dropdown link<\/a>");
document.write("							<div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"navbarDropdownMenuLink\">");
document.write("								 <a class=\"dropdown-item\" href=\"#\">Action<\/a> <a class=\"dropdown-item\" href=\"#\">Another action<\/a> <a class=\"dropdown-item\" href=\"#\">Something else here<\/a>");
document.write("								<div class=\"dropdown-divider\">");
document.write("								<\/div> <a class=\"dropdown-item\" href=\"#\">Separated link<\/a>");
document.write("							<\/div>");
document.write("						<\/li>");
document.write("					<\/ul>");
document.write("				<\/div>");
document.write("			<\/nav>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/div>");
document.write("");
document.write("    <script src=\"js\/jquery.min.js\"><\/script>");
document.write("    <script src=\"js\/bootstrap.min.js\"><\/script>");
document.write("    <script src=\"js\/scripts.js\"><\/script>");
